/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package test;

import javax.swing.JOptionPane;

/**
 *
 * @author Aury
 */
public class FRM_ESTUDIANTE extends javax.swing.JFrame {
    private EstudianteManager manager;


    /**
     * Creates new form Estudiante
     */
    public FRM_ESTUDIANTE() {
       initComponents();
        manager = new EstudianteManager();
        manager.loadFromFile("estudiantes.txt"); // Cargar los datos al iniciar
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_apellido = new javax.swing.JTextField();
        txt_cedula = new javax.swing.JTextField();
        btn_ingresarEstudiante = new javax.swing.JButton();
        cmb_grado = new javax.swing.JComboBox<>();
        cmb_edad = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cmb_paralelo = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Aury\\Downloads\\WALPAPERS\\Estudiantes.png")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(82, 47, 197, 177));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel2.setText("INGRESO DE ESTUDIANTES");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 22, -1, -1));

        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        jLabel4.setText("Apellido:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        jLabel5.setText("Paralelo:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, -1));

        jLabel6.setText("Cedula:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, -1, -1));

        jLabel7.setText("Edad:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, -1, -1));
        jPanel1.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 150, -1));
        jPanel1.add(txt_apellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 290, 150, -1));
        jPanel1.add(txt_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 150, -1));

        btn_ingresarEstudiante.setText("Insertar");
        btn_ingresarEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarEstudianteActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ingresarEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 90, 40));

        cmb_grado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "8vo ", "9no", "10mo", "1 bachillerato", "2 bachillerato", "3 bachillerato" }));
        cmb_grado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_gradoActionPerformed(evt);
            }
        });
        jPanel1.add(cmb_grado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 150, -1));

        cmb_edad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione ...", "12", "13", "14", "15", "16", "17", "18", "19", " " }));
        jPanel1.add(cmb_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 150, -1));

        jLabel8.setText("Grado:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, -1));

        cmb_paralelo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione...", "A", "B", "C", "D" }));
        jPanel1.add(cmb_paralelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 390, 150, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ingresarEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarEstudianteActionPerformed
        // TODO add your handling code here:
          // Leer datos de los campos de texto
        String cedula = txt_cedula.getText().trim();
        String nombre = txt_nombre.getText().trim();
        String apellido = txt_apellido.getText().trim();
         String edadStr = (String) cmb_edad.getSelectedItem(); // Obtener la edad seleccionada
         String grado = (String) cmb_grado.getSelectedItem();
          String paralelo= (String) cmb_paralelo.getSelectedItem();// Obtener el grado seleccionado

         // Validación para asegurarse de que la cédula no tenga más de 10 dígitos
       
        // Validación para asegurarse de que todos los campos se ingresen
        if (cedula.isEmpty() || nombre.isEmpty() || apellido.isEmpty() || edadStr == null || grado == null || paralelo == null||paralelo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
         // Validación para asegurarse de que la cédula tenga exactamente 10 dígitos
        if (cedula.length() != 10) {
            JOptionPane.showMessageDialog(this, "La cédula debe tener 10 dígitos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
          // Validación para asegurarse de que la edad y el grado sean válidos
        if (edadStr.isEmpty() || grado.isEmpty() || paralelo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, seleccione una edad y un grado válidos.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
       int edad;
        try {
            edad = Integer.parseInt(edadStr);
            if (edad <= 0) {
                throw new NumberFormatException("La edad debe ser un número positivo.");
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "La edad debe ser un número positivo.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Crear el objeto ESTUDIANTE
        ESTUDIANTE estudiante = new ESTUDIANTE(cedula, nombre, apellido, edad, grado,paralelo);

        // Agregar el estudiante usando el manager
        if (manager.addEstudiante(estudiante)) {
            JOptionPane.showMessageDialog(this, "Estudiante añadido exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            manager.saveToFile("estudiantes.txt"); // Guardar la información
        } else {
            JOptionPane.showMessageDialog(this, "El estudiante ya existe.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }

        // Limpiar los campos de texto
        txt_cedula.setText("");
        txt_nombre.setText("");
        txt_apellido.setText("");
         cmb_edad.setSelectedIndex(0); // Restablecer la selección del JComboBox
        cmb_grado.setSelectedIndex(0);
         cmb_paralelo.setSelectedIndex(0);// Restablecer la selección del JComboBox
        
    }//GEN-LAST:event_btn_ingresarEstudianteActionPerformed

    private void cmb_gradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_gradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_gradoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_ESTUDIANTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_ESTUDIANTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_ESTUDIANTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_ESTUDIANTE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_ESTUDIANTE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ingresarEstudiante;
    private javax.swing.JComboBox<String> cmb_edad;
    private javax.swing.JComboBox<String> cmb_grado;
    private javax.swing.JComboBox<String> cmb_paralelo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_apellido;
    private javax.swing.JTextField txt_cedula;
    private javax.swing.JTextField txt_nombre;
    // End of variables declaration//GEN-END:variables
}
